name: Bash CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  disk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run disk check script
        run: |
          chmod +x disk_check.sh
          ./disk_check.sh
